package main.java.main;

import javax.swing.JButton;
import javax.swing.JMenuItem;

import main.java.controller.AdicionarClienteController;
import main.java.controller.AdicionarMesaController;
import main.java.controller.FilaDeEsperaController;
import main.java.controller.ListarCardapioController;
import main.java.controller.ListarClienteController;
import main.java.controller.ListarHistoricoController;
import main.java.controller.ListarMesaController;
import main.java.controller.ListarFaturamentoController;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author delfin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        // Restaurante restaurante = Restaurante.getInstance();
        this.setVisible(true);

    }

    public JButton getExibirAtendimentosMenuBtn() {
        return ExibirAtendimentosMenuBtn;
    }

    public void setExibirAtendimentosMenuBtn(JButton ExibirAtendimentosMenuBtn) {
        this.ExibirAtendimentosMenuBtn = ExibirAtendimentosMenuBtn;
    }

    public JButton getExibirListaDeEsperaMenuBtn() {
        return ExibirListaDeEsperaMenuBtn;
    }

    public void setExibirListaDeEsperaMenuBtn(JButton ExibirListaDeEsperaMenuBtn) {
        this.ExibirListaDeEsperaMenuBtn = ExibirListaDeEsperaMenuBtn;
    }

    public JButton getAdicionarMesaMenuBtn() {
        return adicionarMesaMenuBtn;
    }

    public void setAdicionarMesaMenuBtn(JButton adicionarMesaMenuBtn) {
        this.adicionarMesaMenuBtn = adicionarMesaMenuBtn;
    }

    public JButton getIniciarAtendimentoMenuBtn() {
        return iniciarAtendimentoMenuBtn;
    }

    public void setIniciarAtendimentoMenuBtn(JButton iniciarAtendimentoMenuBtn) {
        this.iniciarAtendimentoMenuBtn = iniciarAtendimentoMenuBtn;
    }

   

    public JButton getExibirCardapioMenuBtn() {
        return exibirCardapioMenuBtn;
    }

    public void setExibirCardapioMenuBtn(JButton exibirCardapioMenuBtn) {
        this.exibirCardapioMenuBtn = exibirCardapioMenuBtn;
    }

    public JButton getExibirHistoricoBtn() {
        return exibirHistoricoBtn;
    }

    public void setExibirHistoricoBtn(JButton exibirHistoricoBtn) {
        this.exibirHistoricoBtn = exibirHistoricoBtn;
    }

    public JButton getExibirMesasDisponiveisMenuBtn() {
        return exibirMesasDisponiveisMenuBtn;
    }

    public void setExibirMesasDisponiveisMenuBtn(JButton exibirMesasDisponiveisMenuBtn) {
        this.exibirMesasDisponiveisMenuBtn = exibirMesasDisponiveisMenuBtn;
    }

    public JButton getExibirPagamentosBtn() {
        return exibirPagamentosBtn;
    }

    public void setExibirPagamentosBtn(JButton exibirPagamentosBtn) {
        this.exibirPagamentosBtn = exibirPagamentosBtn;
    }

    public JButton getExitMenuBtn() {
        return exitMenuBtn;
    }

    public void setExitMenuBtn(JButton exitMenuBtn) {
        this.exitMenuBtn = exitMenuBtn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iniciarAtendimentoMenuBtn = new javax.swing.JButton();
        ExibirListaDeEsperaMenuBtn = new javax.swing.JButton();
        ExibirAtendimentosMenuBtn = new javax.swing.JButton();
        exibirMesasDisponiveisMenuBtn = new javax.swing.JButton();
        exibirCardapioMenuBtn = new javax.swing.JButton();
        exibirHistoricoBtn = new javax.swing.JButton();
        adicionarMesaMenuBtn = new javax.swing.JButton();
        exitMenuBtn = new javax.swing.JButton();
        exibirPagamentosBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Restaurante Javengers");

        iniciarAtendimentoMenuBtn.setText("Iniciar atendimento");
        iniciarAtendimentoMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarAtendimentoMenuBtnActionPerformed(evt);
            }
        });

        ExibirListaDeEsperaMenuBtn.setText("Exibir lista de espera");
        ExibirListaDeEsperaMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExibirListaDeEsperaMenuBtnActionPerformed(evt);
            }
        });

        ExibirAtendimentosMenuBtn.setText("Fazer atendimento");
        ExibirAtendimentosMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExibirAtendimentosMenuBtnActionPerformed(evt);
            }
        });

        exibirMesasDisponiveisMenuBtn.setText("Exibir mesas");
        exibirMesasDisponiveisMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirMesasDisponiveisMenuBtnActionPerformed(evt);
            }
        });

        exibirCardapioMenuBtn.setText("Exibir cardápio");
        exibirCardapioMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirCardapioMenuBtnActionPerformed(evt);
            }
        });

        exibirHistoricoBtn.setText("Exibir histórico");
        exibirHistoricoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirHistoricoBtnActionPerformed(evt);
            }
        });

        adicionarMesaMenuBtn.setText("Adicionar mesa");
        adicionarMesaMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarMesaMenuBtnActionPerformed(evt);
            }
        });

        exitMenuBtn.setText("Sair");
        exitMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuBtnActionPerformed(evt);
            }
        });

        exibirPagamentosBtn.setText("Exibir pagamentos");
        exibirPagamentosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirPagamentosBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ExibirListaDeEsperaMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exibirMesasDisponiveisMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exibirCardapioMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exibirHistoricoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adicionarMesaMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ExibirAtendimentosMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iniciarAtendimentoMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exibirPagamentosBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(exitMenuBtn)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(iniciarAtendimentoMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ExibirAtendimentosMenuBtn)
                .addGap(18, 18, 18)
                .addComponent(ExibirListaDeEsperaMenuBtn)
                .addGap(18, 18, 18)
                .addComponent(exibirMesasDisponiveisMenuBtn)
                .addGap(18, 18, 18)
                .addComponent(exibirCardapioMenuBtn)
                .addGap(18, 18, 18)
                .addComponent(exibirHistoricoBtn)
                .addGap(18, 18, 18)
                .addComponent(adicionarMesaMenuBtn)
                .addGap(18, 18, 18)
                .addComponent(exibirPagamentosBtn)
                .addGap(18, 18, 18)
                .addComponent(exitMenuBtn)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>                        

    private void iniciarAtendimentoMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
        new AdicionarClienteController();
    }                                                         

    private void ExibirListaDeEsperaMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // TODO add your handling code here:
        new FilaDeEsperaController();
    }                                                          

    private void ExibirAtendimentosMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
        new ListarClienteController();
    }                                                         

    private void exibirMesasDisponiveisMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
        new ListarMesaController();
    }                                                             

    private void exibirCardapioMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        new ListarCardapioController();
    }                                                     

    private void exibirHistoricoBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        new ListarHistoricoController();
    }                                                  

    private void adicionarMesaMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        new AdicionarMesaController();
    }                                                    

    private void exibirPagamentosBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        new ListarFaturamentoController();
    }                                                   

    private void exitMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        this.dispose();
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ExibirAtendimentosMenuBtn;
    private javax.swing.JButton ExibirListaDeEsperaMenuBtn;
    private javax.swing.JButton adicionarMesaMenuBtn;
    private javax.swing.JButton exibirCardapioMenuBtn;
    private javax.swing.JButton exibirHistoricoBtn;
    private javax.swing.JButton exibirMesasDisponiveisMenuBtn;
    private javax.swing.JButton exibirPagamentosBtn;
    private javax.swing.JButton exitMenuBtn;
    private javax.swing.JButton iniciarAtendimentoMenuBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
