package main;

import main.java.controller.AdicionarClienteController;
import main.java.controller.AdicionarMesaController;
import main.java.controller.ListarClienteController;
import main.java.controller.ListarMesaController;
import main.java.view.CardapioView;
import main.java.view.ComandaView;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author danil
 */
public class Main extends javax.swing.JFrame {

    private CardapioView view;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
       //Restaurante restaurante = Restaurante.getInstance();
        this.setVisible(true);
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        AendimentoMenuBtn = new javax.swing.JMenu();
        iniciarAtendimentoMenuBtn = new javax.swing.JMenuItem();
        exitMenuBtn = new javax.swing.JMenuItem();
        ViewMenuBtn = new javax.swing.JMenu();
        ExibirAtendimentosMenuBtn = new javax.swing.JMenuItem();
        ExibirListaDeEsperaMenuBtn = new javax.swing.JMenuItem();
        exibirMesasDisponiveisMenuBtn = new javax.swing.JMenuItem();
        exibirCardapioMenuBtn = new javax.swing.JMenuItem();
        AcoesMenuBtn = new javax.swing.JMenu();
        adicionarMesaMenuBtn = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Restaurante Javengers");

        AendimentoMenuBtn.setText("Atendimento");

        iniciarAtendimentoMenuBtn.setText("Iniciar Atendimento");
        iniciarAtendimentoMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarAtendimentoMenuBtnActionPerformed(evt);
            }
        });
        AendimentoMenuBtn.add(iniciarAtendimentoMenuBtn);

        exitMenuBtn.setText("Exit");
        exitMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuBtnActionPerformed(evt);
            }
        });
        AendimentoMenuBtn.add(exitMenuBtn);

        jMenuBar1.add(AendimentoMenuBtn);

        ViewMenuBtn.setText("View");

        ExibirAtendimentosMenuBtn.setText("Exibir Atendimentos");
        ExibirAtendimentosMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExibirAtendimentosMenuBtnActionPerformed(evt);
            }
        });
        ViewMenuBtn.add(ExibirAtendimentosMenuBtn);

        ExibirListaDeEsperaMenuBtn.setText("Exibir Lista de Espera");
        ExibirListaDeEsperaMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExibirListaDeEsperaMenuBtnActionPerformed(evt);
            }
        });
        ViewMenuBtn.add(ExibirListaDeEsperaMenuBtn);

        exibirMesasDisponiveisMenuBtn.setText("Exibir Mesas Disponiveis");
        exibirMesasDisponiveisMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirMesasDisponiveisMenuBtnActionPerformed(evt);
            }
        });
        ViewMenuBtn.add(exibirMesasDisponiveisMenuBtn);

        exibirCardapioMenuBtn.setText("Exibir Cardápio");
        exibirCardapioMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirCardapioMenuBtnActionPerformed(evt);
            }
        });
        ViewMenuBtn.add(exibirCardapioMenuBtn);

        jMenuBar1.add(ViewMenuBtn);

        AcoesMenuBtn.setText("Ações");

        adicionarMesaMenuBtn.setText("Adicionar Mesa");
        adicionarMesaMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarMesaMenuBtnActionPerformed(evt);
            }
        });
        AcoesMenuBtn.add(adicionarMesaMenuBtn);

        jMenuBar1.add(AcoesMenuBtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void iniciarAtendimentoMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
       new AdicionarClienteController();
    }                                                         

    private void exitMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            

        this.dispose();
        
    }                                           

    private void ExibirListaDeEsperaMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                           
       // new ListaDeEsperaController();        
    }                                                          

    private void exibirMesasDisponiveisMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
       new ListarMesaController();
    }                                                             

    private void ExibirAtendimentosMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
       new ListarClienteController();
    }                                                         

    private void adicionarMesaMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        new AdicionarMesaController();
    }                                                    

    private void exibirCardapioMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        // ExibirCardapioController();
    }                                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenu AcoesMenuBtn;
    private javax.swing.JMenu AendimentoMenuBtn;
    private javax.swing.JMenuItem ExibirAtendimentosMenuBtn;
    private javax.swing.JMenuItem ExibirListaDeEsperaMenuBtn;
    private javax.swing.JMenu ViewMenuBtn;
    private javax.swing.JMenuItem adicionarMesaMenuBtn;
    private javax.swing.JMenuItem exibirCardapioMenuBtn;
    private javax.swing.JMenuItem exibirMesasDisponiveisMenuBtn;
    private javax.swing.JMenuItem exitMenuBtn;
    private javax.swing.JMenuItem iniciarAtendimentoMenuBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration                   
}
