/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.view;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JToggleButton;

/**
 *
 * @author danil
 */
public class ListarClienteView extends javax.swing.JFrame {

        public ListarClienteView() {
                initComponents();
        }

        public JButton getBtnEditar() {
                return btnEditar;
        }

        public JToggleButton getBtnFazerPedido() {
                return btnFazerPedido;
        }

        public void setBtnFazerPedido(JToggleButton btnFazerPedido) {
                this.btnFazerPedido = btnFazerPedido;
        }

        public JButton getBtnExcluir() {
                return btnExcluir;
        }

        public JButton getBtnVoltar() {
                return btnVoltar;
        }

        public JTable getTbClientes() {
                return tbClientes;
        }

        public void setTbClientes(JTable tbClientes) {
                this.tbClientes = tbClientes;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jScrollPane2 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                btnVoltar = new javax.swing.JButton();
                btnEditar = new javax.swing.JButton();
                btnExcluir = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                tbClientes = new javax.swing.JTable();
                btnFazerPedido = new javax.swing.JToggleButton();

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4"
                                }));
                jScrollPane2.setViewportView(jTable1);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                btnVoltar.setText("Voltar");

                btnEditar.setText("Encerrar Atendimento");

                btnExcluir.setText("Excluir");

                tbClientes.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4"
                                }));
                jScrollPane1.setViewportView(tbClientes);

                btnFazerPedido.setText("Fazer Pedido");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                0,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(0, 18, Short.MAX_VALUE)
                                                                                                .addComponent(btnFazerPedido)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(btnExcluir)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(btnEditar)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(btnVoltar)))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                136,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnVoltar)
                                                                                .addComponent(btnEditar)
                                                                                .addComponent(btnExcluir)
                                                                                .addComponent(btnFazerPedido))
                                                                .addContainerGap()));

                pack();
        }// </editor-fold>

        /**
         * @param args the command line arguments
         */

        // Variables declaration - do not modify
        private javax.swing.JButton btnEditar;
        private javax.swing.JButton btnExcluir;
        private javax.swing.JToggleButton btnFazerPedido;
        private javax.swing.JButton btnVoltar;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable jTable1;
        private javax.swing.JTable tbClientes;
        // End of variables declaration
}
